name: website
description: GroovinChip's website
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_brand_palettes: ^0.3.2
  material_design_icons_flutter: ^5.0.5955-rc.1
  url_launcher: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
